//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SosWeb.dirReport {
    
    
    public partial class SurveyAverageReport {
        
        /// <summary>
        /// PageTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UcentrikWeb.App_Controls.CommonControls.PageTitle PageTitle;
        
        /// <summary>
        /// ReportSurveyAverage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SosWeb.App_Controls.ReportControls.SurveyAverageReport ReportSurveyAverage;
    }
}
